workspace(name = "work")

# Shared block begin
local_repository(
    name = "tools",
    path = "tools",
)
load("@tools//:go.bzl", "go_http_archives", "go_version")
go_http_archives()

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")
load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies", "go_repository")

go_rules_dependencies()
go_register_toolchains(
    version = go_version(),
)
gazelle_dependencies()
# Shared block end

load("@work//a:deps.bzl",  a_local_repositories = "local_repositories", a_repo_mapping = "repo_mapping")
local_repository(
    name = "a",
    path = "a",
    repo_mapping = a_repo_mapping(),
)
a_local_repositories("")

load("@work//b:deps.bzl",  b_local_repositories = "local_repositories", b_repo_mapping = "repo_mapping")
local_repository(
    name = "b",
    path = "b",
    repo_mapping = b_repo_mapping(),
)
b_local_repositories("")

